export const POST_LOGIN="POST_LOGIN";
export const LOGIN_ERROR="LOGIN_ERROR";
export const POST_SIGNUP="POST_SIGNUP";
export const SIGNUP_ERROR="SIGNUP_ERROR";
export const GET_INITIALIZE_PLAYER="GET_INITIALIZE_PLAYER";
export const INITIALIZE_PLAYER_ERROR="INITIALIZE_PLAYER_ERROR";
